name: Dataset
author: kpobococ
category: Native
tags: [dataset, element, elements, data, utilities]
demo: http://jsfiddle.net/GeQhk/
current: 1.0.0
description: "adds support of HTML5 data attributes"
web: "[mootools.net/forge/p/Dataset](http://mootools.net/forge/p/Dataset)"
license: "MIT License"
sources:
  - "Source/Dataset.js"
